apiVersion: v1
kind: PersistentVolume
metadata:
  name: project2-pv-zakhar
  labels:
    type: local
    namespace: zakhar
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/home/zakhar/project2-pv"

