apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project2-pvc-zakhar
  namespace: zakhar
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: standard  # Must match PV storageClassName
  selector:
    matchLabels:
      namespace: zakhar  # Ensure it binds to your assigned PV
  resources:
    requests:
      storage: 1Gi
