apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project2-pvc-zakhar
  namespace: zakhar
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi

