apiVersion: v1
kind: Service
metadata:
  name: playlists-recommender-service
spec:
  type: NodePort
  selector:
    app: playlists-recommender-frontend
  ports:
    - protocol: TCP
      port: 52002
      targetPort: 52002
      nodePort: 32002
